INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR demo.py:11 error,msg
WARNING demo.py:12 warn msg
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 15:02:47] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -


INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR demo.py:11 error,msg
WARNING demo.py:12 warn msg
INFO demo.py:13 info msg
DEBUG demo.py:14 debug msg
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 15:03:51] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
ERROR __init__.py:98 Error: Directory migrations already exists and is not empty
ERROR __init__.py:98 Error: Directory migrations already exists and is not empty
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR app.py:1891 Exception on /static/html/index.html [GET]
Traceback (most recent call last):
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    ctx.push()
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/ctx.py", line 390, in push
    self.session = session_interface.open_session(self.app, self.request)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask_session/sessions.py", line 132, in open_session
    val = self.redis.get(self.key_prefix + sid)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/client.py", line 1606, in get
    return self.execute_command('GET', name)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to 127.0.0.1:6379. Connection refused.
ERROR app.py:1975 Request finalizing failed with an error while handling an error
Traceback (most recent call last):
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    ctx.push()
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/ctx.py", line 390, in push
    self.session = session_interface.open_session(self.app, self.request)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask_session/sessions.py", line 132, in open_session
    val = self.redis.get(self.key_prefix + sid)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/client.py", line 1606, in get
    return self.execute_command('GET', name)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to 127.0.0.1:6379. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/app.py", line 1970, in finalize_request
    response = self.process_response(response)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/app.py", line 2269, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask_session/sessions.py", line 145, in save_session
    if session.modified:
AttributeError: 'NoneType' object has no attribute 'modified'
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:20:05] "[35m[1mGET /static/html/index.html HTTP/1.1[0m" 500 -
ERROR app.py:1891 Exception on /api/v1.0/index [GET]
Traceback (most recent call last):
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    ctx.push()
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/ctx.py", line 390, in push
    self.session = session_interface.open_session(self.app, self.request)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask_session/sessions.py", line 132, in open_session
    val = self.redis.get(self.key_prefix + sid)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/client.py", line 1606, in get
    return self.execute_command('GET', name)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to 127.0.0.1:6379. Connection refused.
ERROR app.py:1975 Request finalizing failed with an error while handling an error
Traceback (most recent call last):
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    ctx.push()
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/ctx.py", line 390, in push
    self.session = session_interface.open_session(self.app, self.request)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask_session/sessions.py", line 132, in open_session
    val = self.redis.get(self.key_prefix + sid)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/client.py", line 1606, in get
    return self.execute_command('GET', name)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to 127.0.0.1:6379. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/app.py", line 1970, in finalize_request
    response = self.process_response(response)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/app.py", line 2269, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask_session/sessions.py", line 145, in save_session
    if session.modified:
AttributeError: 'NoneType' object has no attribute 'modified'
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:20:19] "[35m[1mGET /api/v1.0/index HTTP/1.1[0m" 500 -
ERROR app.py:1891 Exception on /api/v1.0/index [GET]
Traceback (most recent call last):
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    ctx.push()
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/ctx.py", line 390, in push
    self.session = session_interface.open_session(self.app, self.request)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask_session/sessions.py", line 132, in open_session
    val = self.redis.get(self.key_prefix + sid)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/client.py", line 1606, in get
    return self.execute_command('GET', name)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to 127.0.0.1:6379. Connection refused.
ERROR app.py:1975 Request finalizing failed with an error while handling an error
Traceback (most recent call last):
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    ctx.push()
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/ctx.py", line 390, in push
    self.session = session_interface.open_session(self.app, self.request)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask_session/sessions.py", line 132, in open_session
    val = self.redis.get(self.key_prefix + sid)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/client.py", line 1606, in get
    return self.execute_command('GET', name)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to 127.0.0.1:6379. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/app.py", line 1970, in finalize_request
    response = self.process_response(response)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/app.py", line 2269, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask_session/sessions.py", line 145, in save_session
    if session.modified:
AttributeError: 'NoneType' object has no attribute 'modified'
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:20:21] "[35m[1mGET /api/v1.0/index HTTP/1.1[0m" 500 -
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR app.py:1891 Exception on /api/v1.0/index [GET]
Traceback (most recent call last):
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    ctx.push()
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/ctx.py", line 390, in push
    self.session = session_interface.open_session(self.app, self.request)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask_session/sessions.py", line 132, in open_session
    val = self.redis.get(self.key_prefix + sid)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/client.py", line 1606, in get
    return self.execute_command('GET', name)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to 127.0.0.1:6379. Connection refused.
ERROR app.py:1975 Request finalizing failed with an error while handling an error
Traceback (most recent call last):
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    ctx.push()
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/ctx.py", line 390, in push
    self.session = session_interface.open_session(self.app, self.request)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask_session/sessions.py", line 132, in open_session
    val = self.redis.get(self.key_prefix + sid)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/client.py", line 1606, in get
    return self.execute_command('GET', name)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to 127.0.0.1:6379. Connection refused.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/app.py", line 1970, in finalize_request
    response = self.process_response(response)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/app.py", line 2269, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask_session/sessions.py", line 145, in save_session
    if session.modified:
AttributeError: 'NoneType' object has no attribute 'modified'
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:24:01] "[35m[1mGET /api/v1.0/index HTTP/1.1[0m" 500 -
ERROR demo.py:11 error,msg
WARNING demo.py:12 warn msg
INFO demo.py:13 info msg
DEBUG demo.py:14 debug msg
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:24:29] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:24:45] "[37mGET /static/html/index.html HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:24:45] "[37mGET /static/plugins/bootstrap/css/bootstrap.min.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:24:45] "[37mGET /static/plugins/font-awesome/css/font-awesome.min.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:24:45] "[37mGET /static/css/reset.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:24:45] "[37mGET /static/plugins/swiper/css/swiper.min.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:24:45] "[37mGET /static/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:24:45] "[37mGET /static/css/ihome/main.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:24:45] "[37mGET /static/css/ihome/index.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:24:45] "[37mGET /static/js/jquery.min.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:24:45] "[37mGET /static/plugins/bootstrap/js/bootstrap.min.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:24:45] "[37mGET /static/plugins/swiper/js/swiper.jquery.min.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:24:45] "[37mGET /static/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:24:45] "[37mGET /static/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:24:45] "[37mGET /static/js/template.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:24:45] "[37mGET /static/js/ihome/index.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:24:45] "[37mGET /static/images/logo@128x59.png HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:24:45] "[37mGET /static/images/home01.jpg HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:24:45] "[37mGET /static/images/home02.jpg HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:24:45] "[37mGET /static/images/home03.jpg HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:24:45] "[37mGET /static/plugins/font-awesome/fonts/fontawesome-webfont.woff2?v=4.6.3 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:24:49] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:24:49] "[37mGET /static/plugins/bootstrap/css/bootstrap.min.css.map HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR app.py:1891 Exception on /index.html [GET]
Traceback (most recent call last):
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: get_html() got an unexpected keyword argument 'html_filr_name'
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:51:23] "[35m[1mGET /index.html HTTP/1.1[0m" 500 -
ERROR app.py:1891 Exception on /index.html [GET]
Traceback (most recent call last):
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
TypeError: get_html() got an unexpected keyword argument 'html_filr_name'
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:51:55] "[35m[1mGET /index.html HTTP/1.1[0m" 500 -
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:52:08] "[37mGET /index.html HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:52:08] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:52:16] "[37mGET /register.html HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:52:16] "[37mGET /static/css/ihome/register.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:52:16] "[37mGET /static/js/ihome/register.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:52:48] "[37mGET /register.html HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:52:48] "[37mGET /static/plugins/bootstrap/css/bootstrap.min.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:52:48] "[37mGET /static/plugins/font-awesome/css/font-awesome.min.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:52:48] "[37mGET /static/css/reset.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:52:48] "[37mGET /static/css/ihome/main.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:52:48] "[37mGET /static/css/ihome/register.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:52:48] "[37mGET /static/js/jquery.min.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:52:48] "[37mGET /static/plugins/bootstrap/js/bootstrap.min.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:52:48] "[37mGET /static/js/ihome/register.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:52:48] "[37mGET /static/images/logo@128x59.png HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:52:48] "[37mGET /static/plugins/font-awesome/fonts/fontawesome-webfont.woff2?v=4.6.3 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:52:48] "[37mGET /static/plugins/bootstrap/css/bootstrap.min.css.map HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:57:05] "[36mGET /register.html HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:57:16] "[37mGET /my.html HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:57:16] "[37mGET /static/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:57:16] "[37mGET /static/css/ihome/my.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:57:16] "[37mGET /static/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:57:16] "[37mGET /static/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:57:16] "[37mGET /static/js/ihome/my.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:57:37] "[36mGET /my.html HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:57:39] "[36mGET /my.html HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:59:22] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:59:32] "[37mGET / HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:59:32] "[37mGET /static/plugins/swiper/css/swiper.min.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:59:32] "[37mGET /static/css/ihome/index.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:59:32] "[37mGET /static/plugins/swiper/js/swiper.jquery.min.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:59:32] "[37mGET /static/js/template.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:59:32] "[37mGET /static/js/ihome/index.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:59:32] "[37mGET /static/images/home01.jpg HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:59:32] "[37mGET /static/images/home02.jpg HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:59:32] "[37mGET /static/images/home03.jpg HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [21/Sep/2020 16:59:32] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR demo.py:11 error,msg
WARNING demo.py:12 warn msg
INFO demo.py:13 info msg
DEBUG demo.py:14 debug msg
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 13:02:42] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 13:02:42] "[36mGET /favicon.ico HTTP/1.1[0m" 304 -
ERROR demo.py:11 error,msg
WARNING demo.py:12 warn msg
INFO demo.py:13 info msg
DEBUG demo.py:14 debug msg
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 13:02:54] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
ERROR demo.py:11 error,msg
WARNING demo.py:12 warn msg
INFO demo.py:13 info msg
DEBUG demo.py:14 debug msg
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 13:03:26] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 13:03:37] "[37mGET /index.html HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 13:03:37] "[36mGET /static/plugins/bootstrap/css/bootstrap.min.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 13:03:37] "[36mGET /static/plugins/font-awesome/css/font-awesome.min.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 13:03:37] "[36mGET /static/css/reset.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 13:03:37] "[36mGET /static/plugins/swiper/css/swiper.min.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 13:03:37] "[36mGET /static/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 13:03:37] "[36mGET /static/css/ihome/main.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 13:03:37] "[36mGET /static/css/ihome/index.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 13:03:37] "[36mGET /static/js/jquery.min.js HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 13:03:37] "[36mGET /static/plugins/swiper/js/swiper.jquery.min.js HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 13:03:37] "[36mGET /static/plugins/bootstrap/js/bootstrap.min.js HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 13:03:37] "[36mGET /static/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 13:03:37] "[36mGET /static/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 13:03:37] "[36mGET /static/js/template.js HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 13:03:37] "[36mGET /static/js/ihome/index.js HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 13:03:37] "[36mGET /static/images/logo@128x59.png HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 13:03:37] "[36mGET /static/images/home01.jpg HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 13:03:37] "[36mGET /static/images/home02.jpg HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 13:03:37] "[36mGET /static/images/home03.jpg HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 13:03:37] "[36mGET /static/plugins/font-awesome/fonts/fontawesome-webfont.woff2?v=4.6.3 HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 13:03:37] "[36mGET /static/plugins/bootstrap/css/bootstrap.min.css.map HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 13:03:37] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 13:04:00] "[37mGET /search.html?aid=&aname=&sd=&ed= HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 13:04:00] "[37mGET /static/css/ihome/search.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 13:04:00] "[37mGET /static/js/ihome/search.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 13:04:00] "[33mGET /static/images/landlord01.jgp HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 15:16:29] "[37mGET /detail.html?id=1 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 15:16:29] "[37mGET /static/css/ihome/detail.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 15:16:29] "[37mGET /static/js/ihome/detail.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 15:16:29] "[37mGET /static/images/landlord01.jpg HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 15:16:29] "[37mGET /static/images/houseicon_sprite.png HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 15:16:29] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 15:16:31] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 15:16:33] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 15:16:34] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 15:16:34] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 15:16:35] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 15:16:35] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 15:16:35] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 15:16:35] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 15:16:35] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 15:16:35] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 15:16:36] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 15:16:36] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 15:16:36] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 15:16:36] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 15:16:36] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 15:16:37] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 15:16:37] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 15:16:37] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 15:16:37] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 15:16:38] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 15:16:39] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [22/Sep/2020 15:16:39] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 11:36:37] "[33mGET /api/v1.0/iamge_codes/123 HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 11:36:50] "[33mGET /api/v1.0/image_codes/123 HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 11:37:23] "[33mGET /api/v1.0/image_codes/123 HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 11:38:24] "[37mGET /api/v1.0/get_image_codes/123 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 11:41:28] "[33mGET /api/v1.0/get_image_codes/ HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 11:41:34] "[37mGET /api/v1.0/get_image_codes/asc HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 11:41:37] "[33mGET /api/v1.0/get_image_codes HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:01:35] "[33mGET /api/v1.0/image_codes HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:01:43] "[33mGET /api/v1.0/image_codes/321 HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:01:45] "[33mGET /api/v1.0/image_codes/321 HTTP/1.1[0m" 404 -
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:02:05] "[37mGET /api/v1.0/image_codes/321 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:02:55] "[37mGET /api/v1.0/image_codes/1234 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:07:25] "[37mGET /api/v1.0/image_codes/1234 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:08:18] "[37mGET /static/html/index.html HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:08:18] "[36mGET /static/plugins/bootstrap/css/bootstrap.min.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:08:18] "[36mGET /static/plugins/font-awesome/css/font-awesome.min.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:08:18] "[36mGET /static/css/reset.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:08:18] "[36mGET /static/plugins/swiper/css/swiper.min.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:08:18] "[36mGET /static/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:08:18] "[36mGET /static/css/ihome/main.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:08:18] "[36mGET /static/css/ihome/index.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:08:18] "[36mGET /static/js/jquery.min.js HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:08:18] "[36mGET /static/plugins/bootstrap/js/bootstrap.min.js HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:08:18] "[36mGET /static/plugins/swiper/js/swiper.jquery.min.js HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:08:18] "[36mGET /static/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:08:18] "[36mGET /static/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:08:18] "[36mGET /static/js/template.js HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:08:18] "[36mGET /static/js/ihome/index.js HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:08:18] "[36mGET /static/images/logo@128x59.png HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:08:18] "[36mGET /static/images/home01.jpg HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:08:18] "[36mGET /static/images/home02.jpg HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:08:18] "[36mGET /static/images/home03.jpg HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:08:18] "[36mGET /static/plugins/font-awesome/fonts/fontawesome-webfont.woff2?v=4.6.3 HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:08:22] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:08:22] "[36mGET /static/plugins/bootstrap/css/bootstrap.min.css.map HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:08:24] "[36mGET /register.html HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:08:24] "[36mGET /static/css/ihome/register.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:08:24] "[36mGET /static/js/ihome/register.js HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:08:33] "[36mGET /index.html HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:08:33] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:08:40] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:26:49] "[37mGET /index.html HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:26:49] "[37mGET /static/plugins/bootstrap/css/bootstrap.min.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:26:49] "[37mGET /static/plugins/font-awesome/css/font-awesome.min.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:26:49] "[37mGET /static/css/reset.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:26:49] "[37mGET /static/plugins/swiper/css/swiper.min.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:26:49] "[37mGET /static/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:26:49] "[37mGET /static/css/ihome/main.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:26:49] "[37mGET /static/css/ihome/index.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:26:49] "[37mGET /static/js/jquery.min.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:26:49] "[37mGET /static/plugins/bootstrap/js/bootstrap.min.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:26:49] "[37mGET /static/plugins/swiper/js/swiper.jquery.min.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:26:49] "[37mGET /static/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:26:49] "[37mGET /static/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:26:49] "[37mGET /static/js/template.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:26:49] "[37mGET /static/js/ihome/index.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:26:49] "[37mGET /static/images/logo@128x59.png HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:26:49] "[37mGET /static/images/home01.jpg HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:26:49] "[37mGET /static/images/home02.jpg HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:26:49] "[37mGET /static/images/home03.jpg HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:26:49] "[37mGET /static/plugins/font-awesome/fonts/fontawesome-webfont.woff2?v=4.6.3 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:26:49] "[37mGET /static/plugins/bootstrap/css/bootstrap.min.css.map HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:26:49] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:27:13] "[36mGET /index.html HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:27:13] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:27:14] "[37mGET /register.html HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:27:14] "[37mGET /static/css/ihome/register.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:27:14] "[37mGET /static/js/ihome/register.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:27:14] "[37mGET /api/v1.0/image_codes/7d94476a-d2c5-4e7c-898c-c0ca59ad0289 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:27:53] "[36mGET /register.html HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:27:53] "[37mGET /api/v1.0/image_codes/354b34f2-f831-49f1-b9ef-dba25ac3eea1 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:27:53] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:28:08] "[37mGET /api/v1.0/image_codes/d482c2f4-dfea-4842-8cf4-f60356191bfb HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:28:11] "[36mGET /register.html HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:28:11] "[37mGET /api/v1.0/image_codes/4cf109a0-7529-4836-bdf8-ee27a567b3a1 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:28:15] "[36mGET /register.html HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:28:15] "[37mGET /api/v1.0/image_codes/d8732f67-7628-45d7-bb3a-780ef72f5667 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 13:28:17] "[37mGET /api/v1.0/image_codes/d6ccefc5-08ed-4eda-92df-c7b6f2b30cb8 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 14:03:09] "[37mGET /api/v1.0/image_codes/5d3f0c56-bf43-4cf4-b702-974640c0df37 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 14:03:11] "[36mGET /register.html HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 14:03:11] "[37mGET /api/v1.0/image_codes/20f9c341-6a99-42e3-9f77-52e6792acf8b HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 14:03:13] "[36mGET /register.html HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 14:03:13] "[37mGET /api/v1.0/image_codes/d4304308-7c4b-4d98-936a-c918a9327ed7 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 14:03:15] "[36mGET /register.html HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 14:03:15] "[37mGET /api/v1.0/image_codes/a1c7bb84-edde-4f45-bf1b-6484abaaacae HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 14:03:16] "[36mGET /register.html HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 14:03:17] "[37mGET /api/v1.0/image_codes/2e4f5aa8-b69f-4ad4-b452-cedd2ca4c489 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 14:03:19] "[36mGET /register.html HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 14:03:19] "[37mGET /api/v1.0/image_codes/c0e19112-b63e-4c14-ac6d-a03e822e11c6 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 14:03:19] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 14:03:19] "[36mGET /register.html HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 14:03:19] "[37mGET /api/v1.0/image_codes/0b6855a6-ec04-46a0-b465-e40559e10113 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 14:03:19] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 14:03:20] "[36mGET /register.html HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 14:03:20] "[37mGET /api/v1.0/image_codes/cbe6c54f-bd10-4cdd-8267-deb664c20dfc HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 14:03:20] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 14:03:20] "[36mGET /register.html HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 14:03:20] "[37mGET /api/v1.0/image_codes/8852e337-ae48-4687-8969-4ef6860c176c HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 14:03:20] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 14:03:21] "[36mGET /register.html HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 14:03:21] "[37mGET /api/v1.0/image_codes/8e1f3194-b872-43e2-a473-1ae8f533f1c8 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Sep/2020 14:03:21] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 09:10:16] "[37mGET / HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 09:10:16] "[36mGET /static/plugins/bootstrap/css/bootstrap.min.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 09:10:16] "[36mGET /static/plugins/font-awesome/css/font-awesome.min.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 09:10:16] "[36mGET /static/css/reset.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 09:10:16] "[36mGET /static/plugins/swiper/css/swiper.min.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 09:10:16] "[36mGET /static/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 09:10:16] "[36mGET /static/css/ihome/main.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 09:10:16] "[36mGET /static/css/ihome/index.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 09:10:16] "[36mGET /static/js/jquery.min.js HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 09:10:16] "[36mGET /static/plugins/bootstrap/js/bootstrap.min.js HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 09:10:16] "[36mGET /static/plugins/swiper/js/swiper.jquery.min.js HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 09:10:16] "[36mGET /static/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 09:10:16] "[36mGET /static/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 09:10:16] "[36mGET /static/js/template.js HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 09:10:16] "[36mGET /static/js/ihome/index.js HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 09:10:16] "[36mGET /static/images/logo@128x59.png HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 09:10:16] "[36mGET /static/images/home01.jpg HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 09:10:16] "[36mGET /static/images/home02.jpg HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 09:10:16] "[36mGET /static/images/home03.jpg HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 09:10:16] "[36mGET /static/plugins/font-awesome/fonts/fontawesome-webfont.woff2?v=4.6.3 HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 09:10:20] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 09:10:20] "[36mGET /static/plugins/bootstrap/css/bootstrap.min.css.map HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 09:10:23] "[36mGET /register.html HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 09:10:23] "[36mGET /static/css/ihome/register.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 09:10:23] "[36mGET /static/js/ihome/register.js HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 09:10:23] "[37mGET /api/v1.0/image_codes/89f44f9b-b305-4714-a5c3-2b465900cac9 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 09:10:30] "[37mGET /api/v1.0/image_codes/0429091a-5414-4a35-a6b1-8f5cea051e53 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 09:13:55] "[37mGET /api/v1.0/image_codes/2d5adeb6-ccb8-473b-bab1-074fa256f365 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 09:15:17] "[33mGET /api/v1.0/sms_codes/18168580698?image_code=image_code_2d5adeb6-ccb8-473b-bab1-074fa256f365&image_code_id=UF4B HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 09:16:11] "[37mGET /api/v1.0/image_codes/1df65abd-48bc-40ee-bc31-d7324fa792f2 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 09:17:10] "[37mGET /api/v1.0/image_codes/fb9f4425-233c-4907-8da9-01f3ab9dcf6f HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 09:17:55] "[33mGET /api/v1.0/sms_codes/18168580698?image_code=image_code_fb9f4425-233c-4907-8da9-01f3ab9dcf6f&image_code_id=TWVM HTTP/1.1[0m" 404 -
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 10:33:37] "[37mGET /api/v1.0/image_codes/e90c2b1b-6236-45aa-b04c-7bd3184be7ca HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 10:34:23] "[33mGET /api/v1.0/sms_codes/18168580698?image_code=image_code_e90c2b1b-6236-45aa-b04c-7bd3184be7ca&image_code_id=BX3P HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 10:34:38] "[33mGET /api/smscode?mobile=18168580698&code=BX3P&codeId=e90c2b1b-6236-45aa-b04c-7bd3184be7ca HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 10:40:06] "[37mGET /api/v1.0/image_codes/520f2977-da94-44cf-8ea1-b7653ba6be04 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 10:41:05] "[33mGET /api/v1.0/sms_codes/18168580698?image_code=YQHT&image_code_id=image_code_520f2977-da94-44cf-8ea1-b7653ba6be04 HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 10:41:58] "[33mGET /api/v1.0/sms_codes/18168580698?image_code_id=image_code_520f2977-da94-44cf-8ea1-b7653ba6be04&image_code=YQHT HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 10:42:31] "[33mGET /api/v1.0/sms_codes/18168580698?image_code_id=520f2977-da94-44cf-8ea1-b7653ba6be04&image_code=YQHT HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 10:42:54] "[33mGET /api/v1.0/sms_codes/18168580698?image_code_id=520f2977-da94-44cf-8ea1-b7653ba6be04&image_code=YQHT HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 10:42:55] "[33mGET /api/v1.0/sms_codes/18168580698?image_code_id=520f2977-da94-44cf-8ea1-b7653ba6be04&image_code=YQHT HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 10:46:41] "[33mGET /api/v1.0/sms_codes/18168580698 HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 10:46:43] "[33mGET /api/v1.0/sms_codes/18168580698 HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 10:47:44] "[33mGET /sms_codes/18168580698 HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 10:47:45] "[33mGET /sms_codes/18168580698 HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 10:47:53] "[33mGET /sms_codes/18168580698 HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 10:48:10] "[36mGET /register.html HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 10:48:10] "[37mGET /api/v1.0/image_codes/df00dda8-6f67-4db7-9186-273fc8dc47ff HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 10:49:02] "[33mGET /image_codes/image_code_df00dda8-6f67-4db7-9186-273fc8dc47ff HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 10:49:18] "[33mGET /API/V1.0/image_codes/image_code_df00dda8-6f67-4db7-9186-273fc8dc47ff HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 10:49:55] "[37mGET /api/v1.0/image_codes/%3Cimage_code_id%3E HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 10:50:48] "[33mGET /api/v1.0/sms_codes/18188111111 HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 11:02:04] "[33mGET /api/v1.0/sms_codes/18188111111 HTTP/1.1[0m" 404 -
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 11:02:20] "[37mGET /api/v1.0/sms_codes/18188111111 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 11:02:29] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 11:02:30] "[37mGET /api/v1.0/image_codes/dac979b4-f116-49a5-a65a-cdfc9ea36fb2 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 11:04:15] "[33mGET /sms_codes/18168580698?image_code_id=dac979b4-f116-49a5-a65a-cdfc9ea36fb2&image_code=HCEN HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 11:04:15] "[37mGET /api/v1.0/sms_codes/18168580698?image_code_id=dac979b4-f116-49a5-a65a-cdfc9ea36fb2&image_code=HCEN HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 11:04:30] "[37mGET /api/v1.0/image_codes/77e60797-e0d9-4370-9802-f5d7f94c74ef HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 11:05:08] "[37mGET /api/v1.0/sms_codes/18168580698?image_code_id=77e60797-e0d9-4370-9802-f5d7f94c74ef&image_code=BQYU HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 11:10:30] "[37mGET /api/v1.0/image_codes/172f8215-efe6-48bb-b89c-66a56424e57d HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 11:11:01] "[37mGET /api/v1.0/sms_codes/18168580698?image_code_id=172f8215-efe6-48bb-b89c-66a56424e57d&image_code=HSVI HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 11:11:57] "[37mGET /api/v1.0/sms_codes/18168580698?image_code_id=172f8215-efe6-48bb-b89c-66a56424e57d&image_code=HSVI HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 11:12:39] "[37mGET /api/v1.0/sms_codes/18168580698?image_code_id=172f8215-efe6-48bb-b89c-66a56424e57d&image_code=HSVI HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 11:13:26] "[37mGET /api/v1.0/sms_codes/18168580698?image_code_id=172f8215-efe6-48bb-b89c-66a56424e57d&image_code=HSVI HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 11:20:52] "[37mGET /api/v1.0/image_codes/0cf63c33-5b08-4c62-b295-148442d4d5fe HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 11:21:25] "[37mGET /api/v1.0/sms_codes/18168580698?image_code_id=0cf63c33-5b08-4c62-b295-148442d4d5fe&image_code=RUVK HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 11:21:45] "[37mGET /api/v1.0/sms_codes/18168580698?image_code_id=0cf63c33-5b08-4c62-b295-148442d4d5fe&image_code=RUVK HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 11:46:18] "[37mGET /api/v1.0/image_codes/f1e824f6-ecb4-4728-8deb-8886d3d44ff5 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 11:46:53] "[37mGET /api/v1.0/sms_codes/18168580698?image_code_id=f1e824f6-ecb4-4728-8deb-8886d3d44ff5&image_code=TRAH HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 14:11:31] "[37mGET /detail.html?id=1 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 14:11:31] "[37mGET /static/css/ihome/detail.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 14:11:31] "[37mGET /static/js/ihome/detail.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 14:11:31] "[37mGET /static/images/landlord01.jpg HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 14:11:31] "[37mGET /static/images/houseicon_sprite.png HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 14:11:31] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 14:13:02] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 14:13:04] "[37mGET /api/v1.0/image_codes/66a6b34f-84b2-4f2f-85bf-289355abd5c2 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 14:13:05] "[37mGET /api/v1.0/image_codes/84270ce1-5ea4-49ef-841b-b92167206f19 HTTP/1.1[0m" 200 -
DEBUG verify_code.py:75 ************************************
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 14:14:12] "[35m[1mGET /api/v1.0/sms_codes/18168580698?image_code_id=84270ce1-5ea4-49ef-841b-b92167206f19&image_code=9XD4 HTTP/1.1[0m" 500 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
ERROR verify_code.py:35 ***************************
ERROR verify_code.py:36 获取图片中。。。
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 14:20:14] "[37mGET /api/v1.0/image_codes/123 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 14:21:00] "[37mGET /api/v1.0/sms_codes/18168580698?image_code_id=84270ce1-5ea4-49ef-841b-b92167206f19&image_code=9XD4 HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
DEBUG verify_code.py:52 ************************************
DEBUG verify_code.py:53 正在获取验证码。。。
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 14:22:35] "[37mGET /api/v1.0/sms_codes/18168580698?image_code_id=84270ce1-5ea4-49ef-841b-b92167206f19&image_code=9XD4 HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
DEBUG verify_code.py:60 ************************************
DEBUG verify_code.py:61 正在获取验证码。。。
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 14:23:16] "[37mGET /api/v1.0/sms_codes/18168580698?image_code_id=84270ce1-5ea4-49ef-841b-b92167206f19&image_code=9XD4 HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
DEBUG verify_code.py:68 ************************************
DEBUG verify_code.py:69 正在获取验证码。。。
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 14:40:44] "[37mGET /api/v1.0/sms_codes/18168580698?image_code_id=84270ce1-5ea4-49ef-841b-b92167206f19&image_code=9XD4 HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
DEBUG verify_code.py:68 ************************************
DEBUG verify_code.py:69 正在获取验证码。。。：None
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 14:41:12] "[37mGET /api/v1.0/sms_codes/18168580698?image_code_id=84270ce1-5ea4-49ef-841b-b92167206f19&image_code=9XD4 HTTP/1.1[0m" 200 -
ERROR verify_code.py:35 ***************************
ERROR verify_code.py:36 获取图片中。。。
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 14:41:23] "[37mGET /api/v1.0/image_codes/55adfa2d-0a77-4cae-b772-59ee53dda459 HTTP/1.1[0m" 200 -
DEBUG verify_code.py:68 ************************************
DEBUG verify_code.py:69 正在获取验证码。。。：b'C7XD'
DEBUG verify_code.py:79 ************************************
DEBUG verify_code.py:80 real_image_code：b'C7XD'
DEBUG verify_code.py:81 image_code：C7XD
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 14:42:05] "[37mGET /api/v1.0/sms_codes/18168580698?image_code_id=55adfa2d-0a77-4cae-b772-59ee53dda459&image_code=C7XD HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
DEBUG verify_code.py:68 ************************************
DEBUG verify_code.py:69 正在获取验证码。。。：b'C7XD'
DEBUG verify_code.py:79 ************************************
DEBUG verify_code.py:80 real_image_code：b'C7XD'
DEBUG verify_code.py:81 image_code：C7XD
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 14:42:55] "[37mGET /api/v1.0/sms_codes/18168580698?image_code_id=55adfa2d-0a77-4cae-b772-59ee53dda459&image_code=C7XD HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
DEBUG verify_code.py:68 ************************************
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 14:48:42] "[35m[1mGET /api/v1.0/sms_codes/18168580698?image_code_id=55adfa2d-0a77-4cae-b772-59ee53dda459&image_code=C7XD HTTP/1.1[0m" 500 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
ERROR verify_code.py:35 ***************************
ERROR verify_code.py:36 获取图片中。。。
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 14:50:46] "[37mGET /api/v1.0/image_codes/78b06640-bd0c-4fb4-85d5-3b08b52a3541 HTTP/1.1[0m" 200 -
DEBUG verify_code.py:68 ************************************
DEBUG verify_code.py:69 正在获取验证码。。。：MORT
DEBUG verify_code.py:79 ************************************
DEBUG verify_code.py:80 real_image_code：b'mort'
DEBUG verify_code.py:81 image_code：b'MORT'
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 14:51:17] "[37mGET /api/v1.0/sms_codes/18168580698?image_code_id=78b06640-bd0c-4fb4-85d5-3b08b52a3541&image_code=MORT HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
DEBUG verify_code.py:69 ************************************
DEBUG verify_code.py:70 正在获取验证码。。。：MORT
ERROR verify_code.py:89 'cryptography' package is required for sha256_password or caching_sha2_password auth methods
DEBUG connectionpool.py:939 Starting new HTTPS connection (1): app.cloopen.com:8883
DEBUG connectionpool.py:433 https://app.cloopen.com:8883 "POST /2013-12-26/Accounts/8a216da874af5fff0174b997014c04eb/SMS/TemplateSMS?sig=C183B71136A1D6F28CAAF0D7E5F9B45F HTTP/1.1" 200 121
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 14:53:09] "[37mGET /api/v1.0/sms_codes/18168580698?image_code_id=78b06640-bd0c-4fb4-85d5-3b08b52a3541&image_code=MORT HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/constants.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
ERROR verify_code.py:35 ***************************
ERROR verify_code.py:36 获取图片中。。。
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 14:55:33] "[37mGET /api/v1.0/image_codes/bbc24470-ce18-4481-acc7-534e95166d7f HTTP/1.1[0m" 200 -
DEBUG verify_code.py:69 ************************************
DEBUG verify_code.py:70 正在获取验证码。。。：XQTB
ERROR verify_code.py:89 'cryptography' package is required for sha256_password or caching_sha2_password auth methods
DEBUG connectionpool.py:939 Starting new HTTPS connection (1): app.cloopen.com:8883
DEBUG connectionpool.py:433 https://app.cloopen.com:8883 "POST /2013-12-26/Accounts/8a216da874af5fff0174b997014c04eb/SMS/TemplateSMS?sig=A4DAA61B7868396E53E4C86F6B0B1B5D HTTP/1.1" 200 121
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 14:56:18] "[37mGET /api/v1.0/sms_codes/18168580698?image_code_id=bbc24470-ce18-4481-acc7-534e95166d7f&image_code=XQTB HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
DEBUG verify_code.py:69 ************************************
DEBUG verify_code.py:70 正在获取验证码。。。：XQTB
ERROR verify_code.py:89 'cryptography' package is required for sha256_password or caching_sha2_password auth methods
DEBUG connectionpool.py:939 Starting new HTTPS connection (1): app.cloopen.com:8883
DEBUG connectionpool.py:433 https://app.cloopen.com:8883 "POST /2013-12-26/Accounts/8a216da874af5fff0174b997014c04eb/SMS/TemplateSMS?sig=1513C07CFF614878A6B57F8BA48BD005 HTTP/1.1" 200 121
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 14:57:06] "[37mGET /api/v1.0/sms_codes/18168580698?image_code_id=bbc24470-ce18-4481-acc7-534e95166d7f&image_code=XQTB HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
DEBUG verify_code.py:69 ************************************
DEBUG verify_code.py:70 正在获取验证码。。。：XQTB
ERROR verify_code.py:89 'cryptography' package is required for sha256_password or caching_sha2_password auth methods
DEBUG connectionpool.py:939 Starting new HTTPS connection (1): app.cloopen.com:8883
DEBUG connectionpool.py:433 https://app.cloopen.com:8883 "POST /2013-12-26/Accounts/8a216da874af5fff0174b997014c04eb/SMS/TemplateSMS?sig=176D3FCB8AD86B78F9108F0818B72A6B HTTP/1.1" 200 121
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 14:57:39] "[37mGET /api/v1.0/sms_codes/18168580698?image_code_id=bbc24470-ce18-4481-acc7-534e95166d7f&image_code=XQTB HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
DEBUG verify_code.py:69 ************************************
DEBUG verify_code.py:70 正在获取验证码。。。：XQTB
ERROR verify_code.py:89 'cryptography' package is required for sha256_password or caching_sha2_password auth methods
DEBUG connectionpool.py:939 Starting new HTTPS connection (1): app.cloopen.com:8883
DEBUG connectionpool.py:433 https://app.cloopen.com:8883 "POST /2013-12-26/Accounts/8a216da874af5fff0174b997014c04eb/SMS/TemplateSMS?sig=4BC3A9FEE56A01613C1AC82DF0585284 HTTP/1.1" 200 121
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 14:58:20] "[37mGET /api/v1.0/sms_codes/18168580698?image_code_id=bbc24470-ce18-4481-acc7-534e95166d7f&image_code=XQTB HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
ERROR verify_code.py:35 ***************************
ERROR verify_code.py:36 获取图片中。。。
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 15:10:39] "[37mGET /api/v1.0/image_codes/68dcf92e-2a26-4a5a-9145-f9468d43d83b HTTP/1.1[0m" 200 -
DEBUG verify_code.py:69 ************************************
DEBUG verify_code.py:70 正在获取验证码。。。：BZHL
DEBUG verify_code.py:85 ************************************
DEBUG verify_code.py:86 real_image_code：bzhl
DEBUG verify_code.py:87 image_code：xqtb
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 15:11:05] "[37mGET /api/v1.0/sms_codes/18168580698?image_code_id=68dcf92e-2a26-4a5a-9145-f9468d43d83b&image_code=XQTB HTTP/1.1[0m" 200 -
ERROR verify_code.py:67 decoding to str: need a bytes-like object, NoneType found
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 15:11:08] "[37mGET /api/v1.0/sms_codes/18168580698?image_code_id=68dcf92e-2a26-4a5a-9145-f9468d43d83b&image_code=XQTB HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
DEBUG verify_code.py:70 ************************************
DEBUG verify_code.py:71 正在获取验证码。。。：None
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 15:14:03] "[37mGET /api/v1.0/sms_codes/18168580698?image_code_id=68dcf92e-2a26-4a5a-9145-f9468d43d83b&image_code=XQTB HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:113  * Restarting with stat
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
ERROR verify_code.py:36 ***************************
ERROR verify_code.py:37 获取图片中。。。
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 15:41:08] "[37mGET /api/v1.0/image_codes/2321e156-ea5a-4b6b-b056-dfa9bc145934 HTTP/1.1[0m" 200 -
DEBUG verify_code.py:71 ************************************
DEBUG verify_code.py:72 正在获取验证码。。。：FWKE
ERROR verify_code.py:106 'cryptography' package is required for sha256_password or caching_sha2_password auth methods
DEBUG connectionpool.py:939 Starting new HTTPS connection (1): app.cloopen.com:8883
DEBUG connectionpool.py:433 https://app.cloopen.com:8883 "POST /2013-12-26/Accounts/8a216da874af5fff0174b997014c04eb/SMS/TemplateSMS?sig=0F835EB672E967FE73C4AB42308785E9 HTTP/1.1" 200 121
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 15:42:04] "[37mGET /api/v1.0/sms_codes/18168580698?image_code_id=2321e156-ea5a-4b6b-b056-dfa9bc145934&image_code=FWKE HTTP/1.1[0m" 200 -
ERROR verify_code.py:36 ***************************
ERROR verify_code.py:37 获取图片中。。。
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 15:42:18] "[37mGET /api/v1.0/image_codes/0205078a-b220-4834-818f-074765b6012e HTTP/1.1[0m" 200 -
DEBUG verify_code.py:71 ************************************
DEBUG verify_code.py:72 正在获取验证码。。。：JLZN
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 15:43:03] "[37mGET /api/v1.0/sms_codes/18168580698?image_code_id=0205078a-b220-4834-818f-074765b6012e&image_code=JLZN HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:29:32] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
ERROR verify_code.py:36 ***************************
ERROR verify_code.py:37 获取图片中。。。
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:30:06] "[37mGET /api/v1.0/image_codes/3a10867d-5b7a-41a3-a692-329c250791b9 HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:31:09] "[37mGET /register.html HTTP/1.1[0m" 200 -
ERROR verify_code.py:36 ***************************
ERROR verify_code.py:37 获取图片中。。。
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:31:09] "[37mGET /api/v1.0/image_codes/5c2465da-e9b2-413a-ad38-09f4eba60bb9 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:34:03] "[36mGET /register.html HTTP/1.1[0m" 304 -
ERROR verify_code.py:36 ***************************
ERROR verify_code.py:37 获取图片中。。。
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:34:03] "[37mGET /api/v1.0/image_codes/c9508192-20a0-4724-9af0-78de1cdc8b7a HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:36:30] "[36mGET /register.html HTTP/1.1[0m" 304 -
ERROR verify_code.py:36 ***************************
ERROR verify_code.py:37 获取图片中。。。
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:36:30] "[37mGET /api/v1.0/image_codes/09faadf5-11e3-49de-9303-afd7e89ba02b HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:36:52] "[37mGET /register.html HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:36:52] "[37mGET /static/plugins/bootstrap/css/bootstrap.min.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:36:52] "[37mGET /static/plugins/font-awesome/css/font-awesome.min.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:36:52] "[37mGET /static/css/ihome/main.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:36:52] "[37mGET /static/css/ihome/register.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:36:52] "[37mGET /static/js/jquery.min.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:36:52] "[37mGET /static/plugins/bootstrap/js/bootstrap.min.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:36:52] "[37mGET /static/js/ihome/register.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:36:52] "[37mGET /static/images/logo@128x59.png HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:36:52] "[37mGET /static/plugins/font-awesome/fonts/fontawesome-webfont.woff2?v=4.6.3 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:36:52] "[37mGET /static/plugins/bootstrap/css/bootstrap.min.css.map HTTP/1.1[0m" 200 -
ERROR verify_code.py:36 ***************************
ERROR verify_code.py:37 获取图片中。。。
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:36:52] "[37mGET /api/v1.0/image_codes/f2f9f863-d49c-4235-a2ed-c3ac8e49226b HTTP/1.1[0m" 200 -
DEBUG verify_code.py:71 ************************************
DEBUG verify_code.py:72 正在获取验证码。。。：WXAU
ERROR verify_code.py:106 'cryptography' package is required for sha256_password or caching_sha2_password auth methods
DEBUG connectionpool.py:939 Starting new HTTPS connection (1): app.cloopen.com:8883
DEBUG connectionpool.py:433 https://app.cloopen.com:8883 "POST /2013-12-26/Accounts/8a216da874af5fff0174b997014c04eb/SMS/TemplateSMS?sig=CFA73766B14C8E36B725F7CDDE5885AD HTTP/1.1" 200 121
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:37:31] "[37mGET /api/v1.0/sms_codes/18168580698?image_code=wxau&image_code_id=f2f9f863-d49c-4235-a2ed-c3ac8e49226b HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:38:40] "[37mGET /register.html HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:38:40] "[37mGET /static/plugins/bootstrap/css/bootstrap.min.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:38:40] "[37mGET /static/plugins/font-awesome/css/font-awesome.min.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:38:40] "[37mGET /static/css/ihome/main.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:38:40] "[37mGET /static/css/ihome/register.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:38:40] "[37mGET /static/js/jquery.min.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:38:40] "[37mGET /static/plugins/bootstrap/js/bootstrap.min.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:38:40] "[37mGET /static/js/ihome/register.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:38:40] "[37mGET /static/images/logo@128x59.png HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:38:41] "[37mGET /static/plugins/font-awesome/fonts/fontawesome-webfont.woff2?v=4.6.3 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:38:41] "[37mGET /static/plugins/bootstrap/css/bootstrap.min.css.map HTTP/1.1[0m" 200 -
ERROR verify_code.py:36 ***************************
ERROR verify_code.py:37 获取图片中。。。
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:38:41] "[37mGET /api/v1.0/image_codes/47890ab2-5592-4b64-82bc-8d05a939066b HTTP/1.1[0m" 200 -
DEBUG verify_code.py:71 ************************************
DEBUG verify_code.py:72 正在获取验证码。。。：UK9C
DEBUG verify_code.py:87 ************************************
DEBUG verify_code.py:88 real_image_code：uk9c
DEBUG verify_code.py:89 image_code：ukqc
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:38:53] "[37mGET /api/v1.0/sms_codes/18168580698?image_code=ukqc&image_code_id=47890ab2-5592-4b64-82bc-8d05a939066b HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:46:34] "[37mGET /register.html HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:46:34] "[37mGET /static/plugins/bootstrap/css/bootstrap.min.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:46:34] "[37mGET /static/plugins/font-awesome/css/font-awesome.min.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:46:34] "[37mGET /static/css/ihome/main.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:46:34] "[37mGET /static/css/ihome/register.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:46:34] "[37mGET /static/js/jquery.min.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:46:34] "[37mGET /static/plugins/bootstrap/js/bootstrap.min.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:46:34] "[37mGET /static/js/ihome/register.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:46:34] "[37mGET /static/images/logo@128x59.png HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:46:34] "[37mGET /static/plugins/font-awesome/fonts/fontawesome-webfont.woff2?v=4.6.3 HTTP/1.1[0m" 200 -
ERROR verify_code.py:36 ***************************
ERROR verify_code.py:37 获取图片中。。。
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:46:34] "[37mGET /api/v1.0/image_codes/d6c86b26-611a-4923-907d-dc438810ca68 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:46:37] "[37mGET /static/plugins/bootstrap/css/bootstrap.min.css.map HTTP/1.1[0m" 200 -
DEBUG verify_code.py:71 ************************************
DEBUG verify_code.py:72 正在获取验证码。。。：E8TV
ERROR verify_code.py:106 'cryptography' package is required for sha256_password or caching_sha2_password auth methods
DEBUG connectionpool.py:939 Starting new HTTPS connection (1): app.cloopen.com:8883
DEBUG connectionpool.py:433 https://app.cloopen.com:8883 "POST /2013-12-26/Accounts/8a216da874af5fff0174b997014c04eb/SMS/TemplateSMS?sig=D666B5084C7D44781784CFF1C2CF1E49 HTTP/1.1" 200 121
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:46:51] "[37mGET /api/v1.0/sms_codes/18168580698?image_code=E8TV&image_code_id=d6c86b26-611a-4923-907d-dc438810ca68 HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:51:17] "[37mGET /register.html HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:51:17] "[37mGET /static/plugins/bootstrap/css/bootstrap.min.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:51:17] "[37mGET /static/plugins/font-awesome/css/font-awesome.min.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:51:17] "[37mGET /static/css/ihome/main.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:51:17] "[37mGET /static/css/ihome/register.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:51:17] "[37mGET /static/js/jquery.min.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:51:17] "[37mGET /static/plugins/bootstrap/js/bootstrap.min.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:51:17] "[37mGET /static/js/ihome/register.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:51:17] "[37mGET /static/images/logo@128x59.png HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:51:17] "[37mGET /static/plugins/font-awesome/fonts/fontawesome-webfont.woff2?v=4.6.3 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:51:17] "[37mGET /static/plugins/bootstrap/css/bootstrap.min.css.map HTTP/1.1[0m" 200 -
ERROR verify_code.py:36 ***************************
ERROR verify_code.py:37 获取图片中。。。
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:51:17] "[37mGET /api/v1.0/image_codes/754f1273-d59f-4611-b148-22a685625f42 HTTP/1.1[0m" 200 -
DEBUG verify_code.py:71 ************************************
DEBUG verify_code.py:72 正在获取验证码。。。：6XKN
ERROR verify_code.py:106 'cryptography' package is required for sha256_password or caching_sha2_password auth methods
DEBUG connectionpool.py:939 Starting new HTTPS connection (1): app.cloopen.com:8883
DEBUG connectionpool.py:433 https://app.cloopen.com:8883 "POST /2013-12-26/Accounts/8a216da874af5fff0174b997014c04eb/SMS/TemplateSMS?sig=E86E2182479131275652E5453197BB31 HTTP/1.1" 200 121
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:51:25] "[37mGET /api/v1.0/sms_codes/18168580698?image_code=6XKN&image_code_id=754f1273-d59f-4611-b148-22a685625f42 HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/api_1_0/verify_code.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
ERROR verify_code.py:36 ***************************
ERROR verify_code.py:37 获取图片中。。。
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:54:13] "[37mGET /api/v1.0/image_codes/ea947380-7966-4000-bed6-30936fe7c1f2 HTTP/1.1[0m" 200 -
DEBUG verify_code.py:71 ************************************
DEBUG verify_code.py:72 正在获取验证码。。。：LIJU
DEBUG verify_code.py:87 ************************************
DEBUG verify_code.py:88 real_image_code：liju
DEBUG verify_code.py:89 image_code：6xkn
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:54:17] "[37mGET /api/v1.0/sms_codes/18168580698?image_code=6XKN&image_code_id=ea947380-7966-4000-bed6-30936fe7c1f2 HTTP/1.1[0m" 200 -
ERROR verify_code.py:36 ***************************
ERROR verify_code.py:37 获取图片中。。。
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:54:21] "[37mGET /api/v1.0/image_codes/3c3ab98e-854e-4583-9764-8de341993b41 HTTP/1.1[0m" 200 -
DEBUG verify_code.py:71 ************************************
DEBUG verify_code.py:72 正在获取验证码。。。：BCJW
ERROR verify_code.py:106 'cryptography' package is required for sha256_password or caching_sha2_password auth methods
DEBUG connectionpool.py:939 Starting new HTTPS connection (1): app.cloopen.com:8883
DEBUG connectionpool.py:433 https://app.cloopen.com:8883 "POST /2013-12-26/Accounts/8a216da874af5fff0174b997014c04eb/SMS/TemplateSMS?sig=441DB3A9820FA03C9445289DE1F6DC45 HTTP/1.1" 200 121
INFO _internal.py:113 127.0.0.1 - - [24/Sep/2020 16:54:28] "[37mGET /api/v1.0/sms_codes/18168580698?image_code=bcjw&image_code_id=3c3ab98e-854e-4583-9764-8de341993b41 HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/api_1_0/__init__.py', reloading
INFO _internal.py:113  * Restarting with stat
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:24:48] "[37mGET / HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:24:48] "[36mGET /static/plugins/bootstrap/css/bootstrap.min.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:24:48] "[37mGET /static/css/reset.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:24:48] "[37mGET /static/plugins/swiper/css/swiper.min.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:24:48] "[37mGET /static/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:24:48] "[37mGET /static/css/ihome/index.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:24:48] "[36mGET /static/plugins/font-awesome/css/font-awesome.min.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:24:48] "[36mGET /static/css/ihome/main.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:24:48] "[36mGET /static/js/jquery.min.js HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:24:48] "[36mGET /static/plugins/bootstrap/js/bootstrap.min.js HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:24:48] "[37mGET /static/plugins/swiper/js/swiper.jquery.min.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:24:48] "[37mGET /static/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:24:48] "[37mGET /static/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:24:48] "[37mGET /static/js/template.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:24:48] "[37mGET /static/js/ihome/index.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:24:48] "[36mGET /static/images/logo@128x59.png HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:24:48] "[37mGET /static/images/home01.jpg HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:24:48] "[37mGET /static/images/home02.jpg HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:24:48] "[37mGET /static/images/home03.jpg HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:24:48] "[36mGET /static/plugins/font-awesome/fonts/fontawesome-webfont.woff2?v=4.6.3 HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:24:50] "[33mGET /static/plugins/swiper/js/maps/swiper.jquery.min.js.map HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:24:50] "[36mGET /static/plugins/bootstrap/css/bootstrap.min.css.map HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:24:52] "[36mGET /register.html HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:24:52] "[36mGET /static/css/ihome/register.css HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:24:52] "[36mGET /static/js/ihome/register.js HTTP/1.1[0m" 304 -
ERROR verify_code.py:36 ***************************
ERROR verify_code.py:37 获取图片中。。。
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:24:52] "[37mGET /api/v1.0/image_codes/4ca46447-7afa-4f05-8e06-767397876363 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:28:56] "[33mGET /api/v1.0/users HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:29:43] "[33mGET /api/v1.0/users HTTP/1.1[0m" 404 -
DEBUG verify_code.py:71 ************************************
DEBUG verify_code.py:72 正在获取验证码。。。：None
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:30:04] "[37mGET /api/v1.0/sms_codes/18168580698?image_code=ubqb&image_code_id=4ca46447-7afa-4f05-8e06-767397876363 HTTP/1.1[0m" 200 -
ERROR verify_code.py:36 ***************************
ERROR verify_code.py:37 获取图片中。。。
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:30:07] "[37mGET /api/v1.0/image_codes/d6ac9a46-7fe0-4381-ad6c-fbda93240d4c HTTP/1.1[0m" 200 -
DEBUG verify_code.py:71 ************************************
DEBUG verify_code.py:72 正在获取验证码。。。：RZFI
DEBUG connectionpool.py:939 Starting new HTTPS connection (1): app.cloopen.com:8883
DEBUG connectionpool.py:433 https://app.cloopen.com:8883 "POST /2013-12-26/Accounts/8a216da874af5fff0174b997014c04eb/SMS/TemplateSMS?sig=2C8882674C9DD00AC05A3729A3AE89CD HTTP/1.1" 200 121
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:30:15] "[37mGET /api/v1.0/sms_codes/18168580698?image_code=rzfi&image_code_id=d6ac9a46-7fe0-4381-ad6c-fbda93240d4c HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:30:34] "[33mGET /api/v1.0/users HTTP/1.1[0m" 404 -
INFO csrf.py:258 The CSRF token is missing.
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:32:15] "[31m[1mPOST /api/v1.0/users HTTP/1.1[0m" 400 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/__init__.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:36:24] "[35m[1mPOST /api/v1.0/users HTTP/1.1[0m" 500 -
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:36:54] "[35m[1mPOST /api/v1.0/users HTTP/1.1[0m" 500 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/api_1_0/passport.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:38:02] "[37mPOST /api/v1.0/users HTTP/1.1[0m" 200 -
ERROR verify_code.py:36 ***************************
ERROR verify_code.py:37 获取图片中。。。
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:39:26] "[37mGET /api/v1.0/image_codes/0fe304b1-c958-4e10-b60c-5ac0d0828a53 HTTP/1.1[0m" 200 -
DEBUG verify_code.py:71 ************************************
DEBUG verify_code.py:72 正在获取验证码。。。：XBFR
DEBUG connectionpool.py:939 Starting new HTTPS connection (1): app.cloopen.com:8883
DEBUG connectionpool.py:433 https://app.cloopen.com:8883 "POST /2013-12-26/Accounts/8a216da874af5fff0174b997014c04eb/SMS/TemplateSMS?sig=475067F7ED24F738FB328FCFADE71565 HTTP/1.1" 200 121
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:39:33] "[37mGET /api/v1.0/sms_codes/18168580698?image_code=xbfr&image_code_id=0fe304b1-c958-4e10-b60c-5ac0d0828a53 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:39:54] "[37mPOST /api/v1.0/users HTTP/1.1[0m" 200 -
ERROR verify_code.py:36 ***************************
ERROR verify_code.py:37 获取图片中。。。
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:40:58] "[37mGET /api/v1.0/image_codes/3f13de02-0e4d-45a8-b612-5ad056506307 HTTP/1.1[0m" 200 -
ERROR verify_code.py:36 ***************************
ERROR verify_code.py:37 获取图片中。。。
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:40:59] "[37mGET /api/v1.0/image_codes/7114bae7-f515-43d1-819a-13a123aee8c7 HTTP/1.1[0m" 200 -
DEBUG verify_code.py:71 ************************************
DEBUG verify_code.py:72 正在获取验证码。。。：9ORR
DEBUG verify_code.py:87 ************************************
DEBUG verify_code.py:88 real_image_code：9orr
DEBUG verify_code.py:89 image_code：90rr
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:41:07] "[37mGET /api/v1.0/sms_codes/18168580698?image_code=90rr&image_code_id=7114bae7-f515-43d1-819a-13a123aee8c7 HTTP/1.1[0m" 200 -
ERROR verify_code.py:36 ***************************
ERROR verify_code.py:37 获取图片中。。。
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:41:11] "[37mGET /api/v1.0/image_codes/307991d9-e14b-4959-b31c-ab7da10e0597 HTTP/1.1[0m" 200 -
DEBUG verify_code.py:71 ************************************
DEBUG verify_code.py:72 正在获取验证码。。。：RIEV
DEBUG verify_code.py:87 ************************************
DEBUG verify_code.py:88 real_image_code：riev
DEBUG verify_code.py:89 image_code：rtev
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:41:15] "[37mGET /api/v1.0/sms_codes/18168580698?image_code=rtev&image_code_id=307991d9-e14b-4959-b31c-ab7da10e0597 HTTP/1.1[0m" 200 -
DEBUG verify_code.py:71 ************************************
DEBUG verify_code.py:72 正在获取验证码。。。：None
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:41:22] "[37mGET /api/v1.0/sms_codes/18168580698?image_code=riev&image_code_id=307991d9-e14b-4959-b31c-ab7da10e0597 HTTP/1.1[0m" 200 -
ERROR verify_code.py:36 ***************************
ERROR verify_code.py:37 获取图片中。。。
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:41:24] "[37mGET /api/v1.0/image_codes/f633a4b8-17af-4a2c-ae95-c258f5156c52 HTTP/1.1[0m" 200 -
DEBUG verify_code.py:71 ************************************
DEBUG verify_code.py:72 正在获取验证码。。。：UMPU
DEBUG connectionpool.py:939 Starting new HTTPS connection (1): app.cloopen.com:8883
DEBUG connectionpool.py:433 https://app.cloopen.com:8883 "POST /2013-12-26/Accounts/8a216da874af5fff0174b997014c04eb/SMS/TemplateSMS?sig=8B80E658F7C203E05574C9446342D106 HTTP/1.1" 200 121
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:41:29] "[37mGET /api/v1.0/sms_codes/18168580698?image_code=umpu&image_code_id=f633a4b8-17af-4a2c-ae95-c258f5156c52 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:41:58] "[37mPOST /api/v1.0/users HTTP/1.1[0m" 200 -
ERROR verify_code.py:36 ***************************
ERROR verify_code.py:37 获取图片中。。。
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:42:59] "[37mGET /api/v1.0/image_codes/e3fd4010-0b51-400f-9b06-eba7a4edf862 HTTP/1.1[0m" 200 -
DEBUG verify_code.py:71 ************************************
DEBUG verify_code.py:72 正在获取验证码。。。：AC8F
DEBUG connectionpool.py:939 Starting new HTTPS connection (1): app.cloopen.com:8883
DEBUG connectionpool.py:433 https://app.cloopen.com:8883 "POST /2013-12-26/Accounts/8a216da874af5fff0174b997014c04eb/SMS/TemplateSMS?sig=0625C4F920FBC447EAA4D2F8B78235A6 HTTP/1.1" 200 121
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:43:20] "[37mGET /api/v1.0/sms_codes/18168580698?image_code=AC8F&image_code_id=e3fd4010-0b51-400f-9b06-eba7a4edf862 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 15:43:55] "[37mPOST /api/v1.0/users HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/api_1_0/passport.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
ERROR verify_code.py:36 ***************************
ERROR verify_code.py:37 获取图片中。。。
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 16:17:57] "[37mGET /api/v1.0/image_codes/2f187d34-7a66-433b-a653-d21bd077b6e7 HTTP/1.1[0m" 200 -
DEBUG verify_code.py:71 ************************************
DEBUG verify_code.py:72 正在获取验证码。。。：KCMJ
DEBUG connectionpool.py:939 Starting new HTTPS connection (1): app.cloopen.com:8883
DEBUG connectionpool.py:433 https://app.cloopen.com:8883 "POST /2013-12-26/Accounts/8a216da874af5fff0174b997014c04eb/SMS/TemplateSMS?sig=36509D91FB4DF8974E1B124D12B1FCDB HTTP/1.1" 200 121
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 16:18:17] "[37mGET /api/v1.0/sms_codes/18168580698?image_code=KCMJ&image_code_id=2f187d34-7a66-433b-a653-d21bd077b6e7 HTTP/1.1[0m" 200 -
INFO passport.py:41 ***************sms_code:250325
ERROR passport.py:44 can only concatenate str (not "bytes") to str
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 16:18:43] "[37mPOST /api/v1.0/users HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/api_1_0/__init__.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO passport.py:41 ***************sms_code:250325
ERROR passport.py:44 can only concatenate str (not "bytes") to str
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 16:22:07] "[37mPOST /api/v1.0/users HTTP/1.1[0m" 200 -
INFO passport.py:41 ***************sms_code:250385
ERROR passport.py:44 can only concatenate str (not "bytes") to str
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 16:22:18] "[37mPOST /api/v1.0/users HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/api_1_0/passport.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO passport.py:41 ***************sms_code:250385
INFO passport.py:42 ***************real_sms_code:b'250325'
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 16:23:08] "[37mPOST /api/v1.0/users HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/api_1_0/passport.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
ERROR passport.py:44 decoding to str: need a bytes-like object, NoneType found
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 16:23:54] "[37mPOST /api/v1.0/users HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PycharmProjects/Flask_iHome/ihome/api_1_0/passport.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
ERROR verify_code.py:36 ***************************
ERROR verify_code.py:37 获取图片中。。。
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 16:25:57] "[37mGET /api/v1.0/image_codes/13f79d35-2d21-46dc-8a4c-7cc4d9d190f3 HTTP/1.1[0m" 200 -
DEBUG verify_code.py:71 ************************************
DEBUG verify_code.py:72 正在获取验证码。。。：8KQR
DEBUG connectionpool.py:939 Starting new HTTPS connection (1): app.cloopen.com:8883
DEBUG connectionpool.py:433 https://app.cloopen.com:8883 "POST /2013-12-26/Accounts/8a216da874af5fff0174b997014c04eb/SMS/TemplateSMS?sig=CDF3BF46B244B08FCE4EEF868633A360 HTTP/1.1" 200 121
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 16:26:18] "[37mGET /api/v1.0/sms_codes/18168580698?image_code=8KQR&image_code_id=13f79d35-2d21-46dc-8a4c-7cc4d9d190f3 HTTP/1.1[0m" 200 -
INFO passport.py:42 ***************sms_code:329646
INFO passport.py:43 ***************real_sms_code:329646
INFO _internal.py:113 127.0.0.1 - - [25/Sep/2020 16:26:38] "[37mPOST /api/v1.0/users HTTP/1.1[0m" 200 -
